language: node_js
node_js:
  - 16

services:
  - docker

# Build and tag
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed mickeyboy16/udagram-api-feed:v1
  - docker build -t udagram-api-feed ./udagram-api-user
  - docker tag udagram-api-feed mickeyboy16/udagram-api-user:v1
  - docker build -t udagram-api-feed ./udagram-frontend
  - docker tag udagram-api-feed mickeyboy16/udagram-frontend:v1
  - docker build -t udagram-api-feed ./udagram-reverseproxy
  - docker tag udagram-api-feed mickeyboy16/udagram-reverseproxy:v1

# Push
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mickeyboy16/udagram-api-feed:v1
  - docker push mickeyboy16/udagram-api-user:v1
  - docker push mickeyboy16/udagram-frontend:v1
  - docker push mickeyboy16/udagram-reverseproxy:v1