# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-feed ./udagram-api-user
- docker build -t udagram-api-feed ./udagram-frontend
- docker build -t udagram-api-feed ./udagram-reverseproxy

# Tagging
- docker tag udagram-api-feed mickeyboy16/udagram-api-feed:v1
- docker tag udagram-api-feed mickeyboy16/udagram-api-user:v1
- docker tag udagram-api-feed mickeyboy16/udagram-frontend:v1
- docker tag udagram-api-feed mickeyboy16/udagram-reverseproxy:v1

# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push mickeyboy16/udagram-api-feed:v1
- docker push mickeyboy16/udagram-api-user:v1
- docker push mickeyboy16/udagram-frontend:v1
- docker push mickeyboy16/udagram-reverseproxy:v1